{% set name = "simple-gcp-object-downloader" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/simple-gcp-object-downloader-{{ version }}.tar.gz
  sha256: b029ed7be9afc58b8a0942ecd2830c3039180fa31b933117ac5ae3ef8dae8b10

build:
  entry_points:
    - download-gcp-object = simple_gcp_object_downloader.download_gcp_object:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - google-cloud-storage >=2.4.0

test:
  imports:
    - simple_gcp_object_downloader
  commands:
    - pip check
    - download-gcp-object --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: 'https://outerbounds.co/'
  summary: 'Simple GCP object downloader'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saikonen
